#!/bin/bash

arm-none-eabi-objcopy -O binary $1.so $1.bin
#arm-none-eabi-objcopy -O binary  --only-section .text --dump-section .got=$1.got.bin $1.{so,bin}
#
name=$(echo $1|tr '-' '_')

cat > $1.js <<END
'use strict';

// AUTOGENERATED FILE
class blob_$name {
  constructor() {
END

#arm-none-eabi-nm -C -g flasher-sam3x.o | awk '{if (!match($3,/^_/)) {sub(/\(\)/,"",$3); print "    this."$3" =  0x"$1";"}}' >> $1.js
arm-none-eabi-nm -C -g $1.so | awk '{sub(/\(\)/,"",$3); print "    this."$3" =  0x"$1";"}' >> $1.js

cat >> $1.js <<END
    this.blob = Buffer.from([
END

od -vt x1 $1.bin | awk '{for(n=2;n<=NF;n++){printf("0x"$n", ")}if(NF>1)print""}' >> $1.js

cat >> $1.js <<END
    ]);
  }
};
module.exports = blob_$name;
END
