#!/bin/bash

arm-none-eabi-objcopy -O binary $1.o $1.bin

name=$(echo $1|tr '-' '_')

cat > $1.js <<END
'use strict';

// AUTOGENERATED FILE
class blob_$name {
  constructor() {
END

arm-none-eabi-nm -C -g flasher-sam3x.o | awk '{if (!match($3,/^_/)) {sub(/\(\)/,"",$3); print "    this."$3" =  0x"$1";"}}' >> $1.js

cat >> $1.js <<END
    };
    this.blob = [
END

od -vt x1 $1.bin | awk '{for(n=2;n<=NF;n++){printf("0x"$n", ")}if(NF>1)print""}' >> $1.js

cat >> $1.js <<END
    ];
  }
};
module.exports = blob_$name;
END
